# random_module_deep_dive.py

from helpers.display_utils import *
import random

def main(topic_number: int):
    print_heading("The `random` Module: Pseudo-Random Numbers", topic_number)
    imp_note_points("""
- The ___random___ module implements pseudo-random number generators for various distributions.
- "Pseudo-random" means the numbers appear random but are generated by a deterministic algorithm.
- This module should NOT be used for security or cryptographic purposes. For that, use the ___secrets___ module.
- It is incredibly useful for simulations, games, statistical sampling, and randomized algorithms.
""")

    # -----------------------------------------------------------------------------------------------------------------------------------------------
    # 1. Functions for Integers
    # -----------------------------------------------------------------------------------------------------------------------------------------------
    print_sub_heading("1. Functions for Integers")

    print_small_sub_heading("a) random.randint(a, b)", True)
    display_note("Returns a random integer N such that `a <= N <= b`. This range is inclusive on both ends.")
    code1 = '''# Get a random integer in an inclusive range
import random
num1 = random.randint(1, 10)
print(f"Random number between 1 and 10 is: {num1}")
num2 = random.randint(1, 10)
print(f"Another random number between 1 and 10 is: {num2}")
#----------------------------------------------------------#'''
    output1 = run_code_snippet(code1)
    show_code_with_output(code1, output1)

    print_small_sub_heading("b) random.randrange(start, stop[, step])",True)
    display_note("Returns a randomly selected element from `range(start, stop, step)`. The `stop` value is exclusive.")
    code2 = '''# Get a random number from a range (exclusive stop)
import random
# Get a random even number between 0 and 100 
even_num1 = random.randrange(0, 101, 2)
print(f"Random even number: {even_num1}")
even_num2 = random.randrange(0, 101, 2)
print(f"Another random even number: {even_num2}")
#------------------------------------------------#'''
    output2 = run_code_snippet(code2)
    show_code_with_output(code2, output2)

    # -----------------------------------------------------------------------------------------------------------------------------------------------
    # 2. Functions for Sequences
    # -----------------------------------------------------------------------------------------------------------------------------------------------
    print_sub_heading("2. Functions for Sequences")
    display_note("These functions allow you to make random selections from lists, tuples, or other sequence types.")

    print_small_sub_heading("a) random.choice(seq)", True)
    display_note("Returns a single random element from a non-empty sequence.")
    code3 = '''# Pick one random item from a list
import random
options = ['rock', 'paper', 'scissors', 'lizard', 'spock']
move1 = random.choice(options)
print(f"Player1 choose: {move1}") 
move2 = random.choice(options)
print(f"Player2 choose: {move2}")
#----------------------------------------------------------#'''
    output3 = run_code_snippet(code3)
    show_code_with_output(code3, output3)

    print_small_sub_heading("b) random.sample(population, k)", True)
    display_note("Returns a list of `k` unique elements chosen from the population sequence. Used for random sampling without replacement.", "tip")
    code4 = '''# Pick a unique sample of 3 items
import random
options = ['rock', 'paper', 'scissors', 'lizard', 'spock']
sample1 = random.sample(options, 3)
print(f"A sample of 3 unique items: {sample1}")
sample2 = random.sample(options, 3)
print(f"Another sample of 3 unique items: {sample2}")
#----------------------------------------------------------#'''
    output4 = run_code_snippet(code4)
    show_code_with_output(code4, output4)

    print_small_sub_heading("c) random.shuffle(x)", True)
    display_note("Shuffles the sequence `x` in place. This means it modifies the original list and returns `None`.", "warning")
    code5 = '''# Shuffle a list in-place
import random
deck = ['Ace', 'King', 'Queen', 'Jack']
print(f"Original deck: {deck}")
random.shuffle(deck) # This modifies the list
print(f"Shuffled deck: {deck}")
#----------------------------------------------#'''
    output5 = run_code_snippet(code5)
    show_code_with_output(code5, output5)

    # -----------------------------------------------------------------------------------------------------------------------------------------------
    # 3. Functions for Floating-Point Numbers
    # -----------------------------------------------------------------------------------------------------------------------------------------------
    print_sub_heading("3. Functions for Floating-Point Numbers")
    
    print_small_sub_heading("a) random.random()", True)
    display_note("Returns the next random floating point number in the range [0.0, 1.0). The endpoint 1.0 is exclusive.")
    code6 = '''# Generate a random float between 0.0 and 1.0
import random
val1 = random.random()
print(f"Random float: {val1}")
val2 = random.random()
print(f"Another random float: {val2}")
#------------------------------#'''
    output6 = run_code_snippet(code6)
    show_code_with_output(code6, output6)

    print_small_sub_heading("b) random.uniform(a, b)", True)
    display_note("Returns a random floating point number N such that `a <= N <= b` or `b <= N <= a`.")
    code7 = '''# Generate a random float within a specific range
import random
score1 = random.uniform(5.5, 99.5)
print(f"Random score: {score1}")
score2 = random.uniform(5.5, 99.5)
print(f"Another random score: {score2}")
#--------------------------------#'''
    output7 = run_code_snippet(code7)
    show_code_with_output(code7, output7)

    # -----------------------------------------------------------------------------------------------------------------------------------------------
    # 4. Reproducibility with Seeding
    # -----------------------------------------------------------------------------------------------------------------------------------------------
    print_sub_heading("4. Reproducibility with Seeding")
    display_note("""The pseudo-random generator can be initialized with a 'seed' value.
Using the same seed will produce the exact same sequence of 'random' numbers every time.""")
    display_note("This is extremely useful for debugging, testing, and creating reproducible simulations.", "example")
    code8 = '''# Demonstrating the effect of random.seed()
import random

# Set a seed to get a predictable sequence
random.seed(42)
print(f"First run with seed 42: {[random.randint(1, 100), random.randint(1, 100)]}")  

# If we reset with the same seed, we get the same sequence
random.seed(42)
print(f"Second run with seed 42: {[random.randint(1, 100), random.randint(1, 100)]}")
#------------------------------------------------------------------------------------#'''
    output8 = run_code_snippet(code8)
    show_code_with_output(code8, output8)

    

if __name__ == "__main__":
    main(1)
